# Generated by Django 5.0.6 on 2024-08-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='reg_name',
        ),
    ]
