# Generated by Django 5.0.6 on 2024-08-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_remove_charity_reg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='reg_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
