# Generated by Django 5.0.6 on 2024-08-12 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0003_charity_reg_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='reg_name',
            new_name='reg_number',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_benefactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charities.benefactor'),
        ),
    ]
