# Generated by Django 4.2.15 on 2024-08-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0004_rename_reg_name_charity_reg_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('P', 'Pending'), ('W', 'Waiting'), ('A', 'Assigned'), ('D', 'Done')], default='P', max_length=1),
        ),
    ]
